// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1UhK9tLi0-D-Fm874LdtN5dqKBg55lBQ',
    appId: '1:821551360275:web:21679f3e94179926fd52e6',
    messagingSenderId: '821551360275',
    projectId: 'mindtrace-cd8ee',
    authDomain: 'mindtrace-cd8ee.firebaseapp.com',
    storageBucket: 'mindtrace-cd8ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0EV5Awn8axw0qhHEHPTL-8TUhaEKIMtY',
    appId: '1:821551360275:android:d7cdc478dccd5521fd52e6',
    messagingSenderId: '821551360275',
    projectId: 'mindtrace-cd8ee',
    storageBucket: 'mindtrace-cd8ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ7sAD8O_sf-KWNaSMlVIXB57uiRUVQF8',
    appId: '1:821551360275:ios:1a813c4141a64567fd52e6',
    messagingSenderId: '821551360275',
    projectId: 'mindtrace-cd8ee',
    storageBucket: 'mindtrace-cd8ee.firebasestorage.app',
    iosBundleId: 'com.example.mindtrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ7sAD8O_sf-KWNaSMlVIXB57uiRUVQF8',
    appId: '1:821551360275:ios:1a813c4141a64567fd52e6',
    messagingSenderId: '821551360275',
    projectId: 'mindtrace-cd8ee',
    storageBucket: 'mindtrace-cd8ee.firebasestorage.app',
    iosBundleId: 'com.example.mindtrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1UhK9tLi0-D-Fm874LdtN5dqKBg55lBQ',
    appId: '1:821551360275:web:98887f2d860c9294fd52e6',
    messagingSenderId: '821551360275',
    projectId: 'mindtrace-cd8ee',
    authDomain: 'mindtrace-cd8ee.firebaseapp.com',
    storageBucket: 'mindtrace-cd8ee.firebasestorage.app',
  );

}